=== JC-LG/xsd-dtd-xml/juegos.dtd
<!ELEMENT juegos (juego)*>
<!ELEMENT juego (nombre|plataforma|precio|sinopsis)*>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre codigo CDATA #REQUIRED idioma CDATA #REQUIRED>
<!ELEMENT plataforma (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #REQUIRED>
<!ELEMENT sinopsis (#PCDATA)>
<!ATTLIST sinopsis codigoDeJuego CDATA #REQUIRED>
<!ENTITY autor "Juan Carlos Ledezma">

=== JC-LG/xsd-dtd-xml/juegos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE juegos SYSTEM "juegos.dtd">
<juegos>
    <juego>
        <nombre codigo="1" idioma="es">Dios de la Guerra</nombre>
        <plataforma>Playstation 5</plataforma>
        <precio moneda="mx">900.00</precio>
        <sinopsis codigoDeJuego="3">Juego de aventura y guerra.</sinopsis>
    </juego>
    <juego>
        <nombre codigo="2" idioma="en">Last of Us</nombre>
        <plataforma>Playstation 5</plataforma>
        <precio moneda="usd">60.00</precio>
        <sinopsis codigoDeJuego="2">Juego de terror.</sinopsis>
    </juego>
    <juego>
        <nombre codigo="3" idioma="en">Last of Us</nombre>
        <plataforma>Playstation 5</plataforma>
        <precio moneda="usd">60.00</precio>
        <sinopsis codigoDeJuego="3">Juego de terror.</sinopsis>
    </juego>
</juegos>
